### ISSUE TITLE
Savatsky Golay Filter Error "Invalid string length" in Google Earth Engine (Javascript)

### ISSUE THREAD

**Issue by XiHuang1999** [open-geocomputing/OpenEarthEngineLibrary#27]
Dear Prof.,
Why do I get an error "Invalid string length" as soon as I add the vegetation index calculation from line  235 to 249 (and add the Vegetation Index return in line 253)?
If I cancel the code from line 235 to 249 (and cancel the return in line 253), it's can run successfully.
I would like to mention that when I added the vegetation index from line 235 to 249, and cancel the Savatsky Golay Filter (line 517 to 558) also works and saves the “interpolatedCol” to the asset.

Glad to hear your comments with this issues! Thx!

GEE code: https://code.earthengine.google.com/13454dcffa046c9b38b1fd5bdec51155
Table2: https://code.earthengine.google.com/?asset=projects/ee-xihuang8899/assets/QTP_StudyArea_BlockSHP_filterSelect

**Comment by mgravey** [comment]
The problem is clearly in your code, probably where you mixed up client and server side code.
For example, you mix up client and server .map().

In fact, I don't now how you make it so far without having issue earlier :)

I suppose the simplest is to change the code to remove all the getInfo(). Once this done it's should almost work by itself.

I could test that the OEEL is not responsable, because the same error arrive before.

The root cause is complicated to find and I maybe wrong, but basically EE has a limited number of operation that can be represented in a computation tree. And i suppose you over shoot this limit, this is because of saying to the server to do an operation for each image, you do on the client the operation for each image and send it back to the server each image.

best,
Mathieu
